export const USER_SET_ACCOUNT = 'USER_SET_ACCOUNT';
export const USER_CLEAR_STORE = 'USER_CLEAR_STORE';

// PV
export const USER_GET_PRIMARY_VALIDATOR_REQUESTED = 'USER_GET_PRIMARY_VALIDATOR_REQUESTED';
export const USER_GET_PRIMARY_VALIDATOR_SUCCESSFUL = 'USER_GET_PRIMARY_VALIDATOR_SUCCESSFUL';
export const USER_GET_PRIMARY_VALIDATOR_FAILED = 'USER_GET_PRIMARY_VALIDATOR_FAILED';

// Balance
export const USER_GET_BALANCE_REQUESTED = 'USER_GET_BALANCE_REQUESTED';
export const USER_GET_BALANCE_SUCCESSFUL = 'USER_GET_BALANCE_SUCCESSFUL';
export const USER_GET_BALANCE_FAILED = 'USER_GET_BALANCE_FAILED';

// Balance
export const USER_GET_TRANSACTIONS_REQUESTED = 'USER_GET_TRANSACTIONS_REQUESTED';
export const USER_GET_TRANSACTIONS_SUCCESSFUL = 'USER_GET_TRANSACTIONS_SUCCESSFUL';
export const USER_GET_TRANSACTIONS_FAILED = 'USER_GET_TRANSACTIONS_FAILED';

// Transfer
export const USER_TRANSFER_REQUESTED = 'USER_TRANSFER_REQUESTED';
export const USER_TRANSFER_SUCCESSFUL = 'USER_TRANSFER_SUCCESSFUL';
export const USER_TRANSFER_FAILED = 'USER_TRANSFER_FAILED';

// Bank
export const USER_SET_BANK = 'USER_SET_BANK';
