export const URLS = {
  about: '/about',
  account: '/account',
  authcheck: '/2fa',
  browser: '/browser',
  client: '/client',
  contact: '/contact',
  dashboard: '/dashboard',
  documentation: '/documentation',
  downloads: '/downloads',
  faq: '/faq',
  history: '/history',
  integration: '/integration',
  landing: '/',
  login: '/login',
  mobile: '/mobile',
  privacy: '/privacy',
  privacypolicy: '/privacy-policy',
  referral: '/referral',
  setup: '/setup',
  signup: '/signup',
  tos: '/terms-of-service',
  transactions: '/transactions',
  wallet: '/wallet',
};
